- README.md
Corrected the spelling of 'voluntarily'.
> Spelling correction on README.md

- fever/fever.go
Please see this: https://github.com/miniflux/miniflux/issues/7
> Fix for unstarring/unsaving bookmark

- ui/static/css/common.css
> Hide horizontal overflow on hiding articles

- reader/sanitizer/sanitizer.go
- reader/sanitizer/sanitizer_test.go
See #157.
Refactored how blacklisted tags are handled so they're easier manage in the future.
> Improve sanitizer to remove style tag contents.

- reader/processor/processor.go
> Processor: Do rewriter before sanitizer for `entry.Content`.

- ui/static/js.go
- ui/static/js/touch_handler.js
> Prevent vertical scrolling on swipe.

- middleware/basic_auth.go
Addresses #205 (per my comment on #209).
Changed error level reporting on API login failure to Error from Info to match the web login reporting.
> Added remote client IP to API login failure error message.

- .travis.yml
https://blog.golang.org/go1.11
> Switch Travis to Go 1.11

- api/feed.go
- api/payload.go
- api/subscription.go
- client/core.go
- database/migration.go
- database/sql.go
- database/sql/schema_version_21.sql
- http/client/client.go
- model/feed.go
- reader/feed/handler.go
- reader/processor/processor.go
- reader/scraper/scraper.go
- reader/subscription/finder.go
- storage/entry_query_builder.go
- storage/feed.go
- template/html/add_subscription.html
- template/html/choose_subscription.html
- template/html/edit_feed.html
- template/views.go
- tests/feed_test.go
- ui/entry_scraper.go
- ui/feed_edit.go
- ui/feed_update.go
- ui/form/feed.go
- ui/form/subscription.go
- ui/subscription_add.go
- ui/subscription_bookmarklet.go
- ui/subscription_choose.go
- ui/subscription_submit.go
> feed processor user agent customization

- template/functions.go
- template/functions_test.go
Fixed #233 with less git changes, to prevent increasing `.git` directory size.
> Unicode complaint truncate function fix

- Makefile
> add openbsd build

- config/config.go
- config/config_test.go
- service/scheduler/scheduler.go
- storage/entry.go
Sorry, I don't read the project structure well, this PR may be a better implement than #292.
> configurable days to archive read item

- Makefile
I put a comment above them saying that they're unsupported as they won't be tested on CI, etc., but they're still nice to have.
> Add more targets to Makefile

- storage/feed.go
This is a minor thing but it was annoying me :)
> Make the feed list order case-insensitive

- template/html/feed_entries.html
- template/views.go
> Use the correct warning if there are no unread entries on the feed_entries page

- reader/sanitizer/sanitizer.go
- reader/sanitizer/sanitizer_test.go
- template/html/bookmark_entries.html
- template/html/category_entries.html
- template/html/entry.html
- template/html/feed_entries.html
- template/html/feeds.html
- template/html/history_entries.html
- template/html/search_entries.html
- template/html/unread_entries.html
- template/views.go
This feature is available only in Chrome >= 76 for now.
See https://web.dev/native-lazy-loading
> Add native lazy loading for images and iframes

- reader/scraper/rules.go
Maybe these defaults could be set as the placeholder values on the Feed edit page. Based on the Site URL
> Update Le Monde scraper rules

- reader/rss/dublincore.go
- reader/rss/feedburner.go
- reader/rss/parser_test.go
- reader/rss/podcast.go
- reader/rss/rss.go
- Add support for Google Play XML namespace
- Improve existing iTunes namespace implementation
> Improve Podcast support (iTunes and Google Play feeds)

- service/httpd/httpd.go
This PR lets miniflux use the same secure TLS configuration options when using LetsEncrypt / autocert as when using a manually specified certificate. It raises the server’s [SSL Labs][ssl] score from a B to an A+ with LetsEncrypt.
[ssl]: https://www.ssllabs.com/ssltest/
> Use secure TLS configuration with LetsEncrypt

- storage/entry_query_builder.go
Introduced in commit 267b7065444b2904e1172817c661709e0b456b80
> Fix SQL injection in full-text search rank ordering

- reader/rewrite/rewrite_functions.go
- reader/rewrite/rewriter.go
- reader/rewrite/rules.go
- reader/sanitizer/sanitizer.go
- Embed Invidious player for invidio.us feeds
- Add new rewrite rule to use Invidious player for Youtube feeds
> Add support for Invidious

- http/response/builder.go
- http/response/builder_test.go
> CSP Update

- service/httpd/httpd.go
> Add /version endpoint

- storage/user.go
> Updating custom css field should also happen when updating the password

- config/config_test.go
- config/options.go
- config/parser.go
- database/migration.go
- database/sql.go
- database/sql/schema_version_30.sql
- miniflux.1
- model/feed.go
- model/feed_test.go
- reader/feed/handler.go
- storage/feed.go
- storage/job.go
detail description in https://github.com/miniflux/miniflux/issues/643
I named the new scheduler "ENTRY_COUNT_BASED".
Suggest a new name please if you can think of a better one.
> Add an alternative Scheduler

- reader/subscription/finder.go
I came across a few blogs that didn't have a `<link rel="alternate">` but still offered a RSS/Atom feed.
This aims at solving this issue for "well known" feed urls, since these urls are often the same.
I'm not familiar with Go so I don't know if my code is very idiomatic but I tried my best to learn by example reading the existing code base.
> Try known urls if no link alternate

- storage/entry.go
As flushing does not archive shared items, the scheduled achieving should not archive the shared items too.
> do not archive shared items

- template/common.go
- template/html/common/feed_list.html
- ui/feed_mark_as_read.go
- ui/ui.go
I've been using this patch on my own build instance, let me know if there's anything else I've have to do
that I didn't cover on this patch
> Allow to mark all unread itens of a feed as read

- database/migration.go
- database/sql.go
- database/sql/schema_version_36.sql
- reader/feed/handler.go
- storage/enclosure.go
- storage/entry.go
- storage/feed.go
Also includes few database improvements:
- Speed up entries clean up with an index and a goroutine
- Avoid the accumulation of enclosures for some feeds
> Use a transaction to refresh and create entries

- reader/sanitizer/sanitizer.go
- reader/sanitizer/sanitizer_test.go
- Add support for picture HTML tag
- Add support for srcset, media, and sizes attributes to img and source tags
> Add sanitizer support for responsive images

- model/feed.go
- model/feed_test.go
- reader/processor/processor.go
- reader/processor/processor_test.go
Avoid looping multiple times across entries
> Refactor entry filtering

- client/core.go
- database/migrations.go
- miniflux.1
- model/user.go
- oauth2/google.go
- oauth2/manager.go
- oauth2/oidc.go
- oauth2/provider.go
- storage/user.go
- template/common.go
- template/html/common/layout.html
- template/html/settings.html
- template/views.go
- ui/form/settings.go
- ui/oauth2_callback.go
- ui/oauth2_redirect.go
- ui/oauth2_unlink.go
- ui/settings_show.go
- ui/static_stylesheet.go
Migrated key/value pairs to specific columns.
> Remove extra column from users table (HSTORE field)

- go.mod
- go.sum
- ui/static_manifest.go
- ui/subscription_bookmarklet.go
It uses [Web Share Target API](https://web.dev/web-share-target/) and works like this:
https://user-images.githubusercontent.com/58525038/103439702-4265e200-4c50-11eb-8dc8-c890cfa28dcf.mp4
You need to add Miniflux to home screen for this to work.
> Subscribe to feeds with the Android Share menu

- model/feed.go
- storage/entry.go
- storage/entry_query_builder.go
- storage/feed.go
- storage/feed_query_builder.go
The feed query builder should help issue #697 and issue #632, if we want to sort feeds on the server.
It also simplifies the storage/feed.go
> create a feed query builder

- database/migrations.go
see https://github.com/miniflux/v2/issues/963
> PostgreSQL index optimizations

- Makefile
- database/migrations.go
The relation "entries_user_feed_idx" already exists
> Fix regression introduced by PR #973

- ui/form/subscription.go
The subscription creation form was ignoring the "fetch_via_proxy" value.
> Don't discard the "Fetch via Proxy" option

- config/config_test.go
- config/options.go
- config/parser.go
- miniflux.1
- storage/feed.go
- storage/job.go
> add global option POLLING_PARSING_ERROR_LIMIT

- http/response/builder.go
- http/response/builder_test.go
- reader/sanitizer/sanitizer.go
- reader/sanitizer/sanitizer_test.go
Only URLs with a mime-type image/* are allowed
> Allow images with data URLs

- http/request/client_ip.go
- http/request/client_ip_test.go
Drops the zone part of the ipv6 address such that it adheres to the `inet` type of Postgres.
This fixes the problem for me locally.
fixes #1008
> add support for ipv6 with zone index

- http/response/builder.go
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
> Add header "Referrer-Policy: no-referrer"

- cli/cli.go
- service/httpd/httpd.go
- storage/feed.go
- storage/storage.go
> Improve health check endpoint to test database connection

- reader/sanitizer/sanitizer.go
- [x ] I have tested my changes
- [x ] I read this document: https://miniflux.app/faq.html#pull-request
resolve #739
> update whitelist fix bilibili video

- cli/cli.go
- cli/health_check.go
- contrib/docker-compose/basic.yml
- contrib/docker-compose/caddy.yml
- contrib/docker-compose/traefik.yml
- miniflux.1
- packaging/docker/Dockerfile
- Add new cli argument: `-healthcheck`
- Add `HEALTHCHECK` instruction to Dockerfile
- Update Docker Compose examples
> Add more extensive healthcheck support

- config/config_test.go
- config/options.go
- config/parser.go
- miniflux.1
- reader/processor/processor.go
- reader/processor/processor_test.go
> Use YouTube video duration as read time

- go.sum
- template/templates/views/entry.html
> Add entry read time on read page

- reader/rss/parser_test.go
- reader/rss/rss.go
- reader/sanitizer/strip_tags.go
for example:
The rss feed https://rsshub.app/github/trending/daily , the item author in the CDATA section.
> Allow CDATA parse author

- template/templates/common/layout.html
- template/templates/views/entry.html
- ui/static/bin/sprite.svg
- ui/static/css/common.css
- ui/static/js/app.js
> Use SVG icons for toast notifications

- storage/feed.go
- storage/user.go
First patch to avoid the app hanging when deleting large feeds
> Improve large feed deletion

- reader/atom/atom_10.go
- reader/atom/atom_10_test.go
> Fix incorrect parsing of Atom entry content of type HTML

- reader/rdf/parser_test.go
- reader/rdf/rdf.go
Example: http://rss.slashdot.org/Slashdot/slashdotMain
> Handle RDF feed with HTML encoded entry title

- reader/atom/atom_10.go
- reader/atom/atom_10_test.go
- Note that Miniflux does not render entry title with HTML tags as of now
- Omit XHTML div element because it should not be part of the content
> Add better support of Atom text constructs

- reader/atom/atom_10.go
- reader/atom/atom_10_test.go
> Improve handling of Atom text content with CDATA

- .github/workflows/ci.yml
- .github/workflows/linters.yml
- client/client.go
- client/request.go
- http/client/response_test.go
- http/route/route.go
- model/user.go
- reader/atom/atom_10.go
- reader/rss/rss.go
- storage/entry_query_builder.go
- storage/feed_query_builder.go
- template/functions.go
- tests/tests.go
- tests/user_test.go
> Setup golangci-lint Github Action

- reader/json/parser.go
> Fix typo in reader/json/doc.go

- template/templates/views/choose_subscription.html
This pull request fixes #1118 .
> Fix filtering doesn't work when selecting from multiple found feeds

- reader/rss/parser_test.go
- reader/rss/rss.go
> Handle RSS feed title with encoded Unicode entities

- config/options.go
- miniflux.1
> Increase default batch size value

- locale/translations/zh_CN.json
> Update a shared entry label translation in zh_CN

- metric/metric.go
- storage/storage.go
> Add database stats to Prometheus exporter

- cli/daemon.go
- config/options.go
- config/parser.go
- storage/storage.go
> Add option to disable watchdog and set default timeout to DB healthcheck

- cli/cli.go
- config/options.go
- config/parser.go
- database/database.go
- miniflux.1
> Add new option DATABASE_CONNECTION_LIFETIME

- config/options.go
- config/parser.go
- miniflux.1
- service/scheduler/scheduler.go
- storage/entry.go
> Add new config option CLEANUP_ARCHIVE_BATCH_SIZE

- template/functions.go
- template/templates/common/layout.html
- ui/static/js/request_builder.js
> Remove invalid CSRF HTML meta tag

- ui/static/js/app.js
- ui/static/js/bootstrap.js
> set items to read on click/middle-click of external link

- storage/feed.go
- ui/static/css/common.css
- ui/static/css/dark.css
- ui/static/css/light.css
- ui/static/css/system.css
> Feeds with errors should appear before unread ones

- template/templates/common/layout.html
- ui/ui.go
> Use unique file names for cache busting instead of query string

- client/request.go
Try to parse the response body from the server when an HTTP 500 is
returned (i.e. http.StatusInternalServerError) as it might contain
useful information. If successful, create a new error and append that
information to the returned error message. Otherwise just maintain the
same behavior
> client: Try to parse response Body on InternalServerError

- .github/workflows/ci.yml
> Add Go 1.17 to GitHub Actions

- reader/scraper/rules.go
> Update scraper rule for theregister.com

- Makefile
- packaging/rpm/Dockerfile
> Build RPM and Debian package with PIE mode enabled

- ui/static/css/common.css
> Fix wrong CSS var

- reader/opml/opml.go
- reader/opml/parser.go
- reader/opml/serializer.go
- reader/opml/serializer_test.go
> Add <head> tag to OPML export

- reader/handler/handler.go
- reader/icon/finder.go
- ui/proxy.go
> Use custom feed user agent to fetch website icon

- ui/proxy.go
> Omit User-Agent header in image proxy to avoid being blocked

- reader/atom/atom_10.go
- reader/atom/atom_10_test.go
- reader/atom/atom_common.go
> Add support for multiple authors in Atom feeds

- packaging/systemd/miniflux.service
> packaging: add Documentation to systemd service

- http/request/params.go
- ui/form/settings.go
> Fix incorrect conversion between integer types

- .github/workflows/linters.yml
> Pin jshint version in linter job

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/linters.yml
> Set read-all permission to GITHUB_TOKEN for CI jobs

- template/templates/views/edit_feed.html
Simply put the Category field first in the feed settings. It is based a) on my personal experience of trying to find it and only finding it through a bit of struggle, b) a prediction that it should probably be one of the most used fields of the field settings. Thanks for making miniflux & for hosting it too.
> Category first in feed settings

- ui/static/js/bootstrap.js
> Add missing event argument to onClick() function call

- template/templates/views/entry.html
> Avoid showing "undefined" when clicking on read/unread

- template/templates/common/settings_menu.html
- template/templates/views/history_entries.html
- template/templates/views/shared_entries.html
- ui/static/bin/sprite.svg
- ui/static/css/common.css
> Add missing page header icons

- ui/static/css/common.css
> Fix CSS hover style for links styled as buttons

- googlereader/handler.go
> Fix google reader api issue #1360.

- template/templates/common/layout.html
- ui/static/js/app.js
- ui/static/js/bootstrap.js
> Add '+' shortcut for new subscription page

- reader/atom/atom_10.go
- reader/atom/atom_10_test.go
> Do not fallback to InnerXML if XHTML title is empty

- reader/atom/atom_03.go
- reader/atom/atom_03_test.go
- reader/atom/atom_10.go
- reader/atom/atom_10_test.go
- reader/json/json.go
- reader/json/parser_test.go
- reader/rss/parser_test.go
- reader/rss/rss.go
- reader/sanitizer/truncate.go
- reader/sanitizer/truncate_test.go
> Use truncated entry description as title if unavailable

- .github/workflows/ci.yml
- .github/workflows/linters.yml
> Add Go 1.18 to GitHub Actions

- .github/workflows/docker.yml
- Makefile
- packaging/docker/alpine/Dockerfile
- packaging/docker/distroless/Dockerfile
> Add distroless Docker image variant

- googlereader/handler.go
Add support for stream IDs of the form `feed/<feed ID>` to the `/reader/api/0/stream/items/ids` Google Reader API endpoint, which allows clients to fetch entry IDs for a specific feed. 
NetNewsWire makes this API call when adding new feeds and other clients may as well too.
> Add support for feed streams to Reader API IDs API

- reader/atom/atom_10.go
- reader/atom/atom_10_test.go
> Try to use outermost element text when title is empty
