reader/scraper/scraper.go
Current behavior: if you have an `iframe` scraper rule, `scrapContent`
tries to return the inner HTML of the `iframe`, which turns up blank.
New behavior: like `img` elements, if an `iframe` is matched by a scraper rule,
the parent element's inner HTML (i.e. the `iframe` is returned).
=> Scrape parent element for iframe

fever/fever.go
Fever API says an empty JSON array is returned when there are no more items to return. 
However, miniflux was omiting the key 'items' from the response entirely when there are no items to return. GO's slice in the return object is initialized to nil and hence json marshal omits the field entirely. This was causing ReadKit on mac to crash on every incremental sync.
=> Fever API: If there are no items to return, return an empty JSON array

reader/sanitizer/sanitizer.go, reader/sanitizer/sanitizer_test.go
Go's x/net/html doesn't handle `noscript` tags well. It assumes the entire contents of any noscript tag is a text node, which is not always the case. There's an [open issue](https://github.com/golang/go/issues/16318) tracking it for two years now but the issue remains.
What I've found is that many sites lazy load images and use noscript as a fall back. Currently the Sanitizer strips noscript but because the subsequent content is returned as a text node it ends up putting HTML in the article. So the article ends up looking like this (with actual HTML code right alongside normal text):
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac urna sed purus mollis convallis ac ut libero. Ut quis.
>
> \<div class="lazyload-fallback">
>     \<img src="medium-res.jpg" alt="">
> …
=> Updated Sanitizer to better handle noscript tags.

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter_test.go
* Only processes images with `src` **and** `title` attributes (others are ignored).
* Processes **all** images in the document (not just the first one).
* Wraps the image and its title attribute in a `figure` tag with the title attribute's contents in a `figcaption` tag.
Updated xkcd rewriter unit test.
Added another xkcd rewriter unit test to check rendering of images without title tags.
---
These changes keep the title text with the image where it's found in the document (versus just appending the first image's title text to the end of the document). It works with simple comics like *xkcd* but also with more complicated articles like the *[What If?](https://what-if.xkcd.com)* blog (by the same author; who in his posts uses multiple images, each with their own title text).
`entryContent` …
=> Refactor AddImageTitle rewriter.

model/theme_test.go
This should have been included in be95e87e0ecd77023dda4f4cf390703e768c9378, sorry.
=> Test for Sans-Serif theme.

reader/sanitizer/sanitizer.go, reader/sanitizer/sanitizer_test.go
Updated iframe unit tests to expect new `sandbox` attribute where appropriate.
Refactored sanitizer.getExtraAttributes() to use `switch` instead of multiple `if` statements.
---
This change further restricts the access an `iframe` has. Tested this against YouTube, Vimeo and SoundCloud embeds. All seem to work.
I also refactored `getExtraAttributes()` because as the number of checks grows, using a switch seems cleaner and is probably a pinch faster.
=> Sandbox iframes when sanitizing.

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter.go, reader/rewrite/rewriter_test.go
Searches image tags for various `data-*` attributes and sets `src` attribute appropriately. Falls back to searching `noscript` for `img` tags.
Includes unit tests.
---
Some web sites use JavaScript to load images only when the image is in the viewport (e.g. when scrolling down the page, images load as that part of the page becomes visible), other sites will load images based on the visitor's screen size (e.g. mobile loads a smaller image than desktop). Scraping sites like this means entries can have no images in them. This rewriter attempts to find the highest quality image and include it.
The `candidateAttrs` values will need to be updated as new sites are reported, etc.
I've been using this code successfully for over a week on an assortment of sites.
=> New `add_dynamic_image` rewriter for JavaScript-loaded images.

config/config.go, filter/image_proxy_filter.go, filter/image_proxy_filter_test.go, template/functions.go
Adds `PROXY_IMAGES` configuration setting to change image proxy filter behaviour:
* `0` = Never proxy.
* `1` = Proxy non-HTTPS (default).
* `2` = Always proxy.
Added additional unit tests.
Addresses #142.
---
If accepted, I'll do a PR for the documentation.
=> Make image proxy filter tunable.

reader/atom/atom.go, reader/atom/parser_test.go
There are atom feeds which use 'published' tag in entry instead of 'updated'. As described [here](https://validator.w3.org/feed/docs/atom.html) 'published' is optional element. It could be used when 'updated' tag is not present for entry.
=> Support for 'published' tag in atom feed

template/common.go, template/html/common/item_meta.html, template/html/entry.html, template/views.go
Sometimes when reading on mobile, the Star/Read links jump to a new line, thus making it hard to touch those links with my fat fingers. By using a non-breaking space, the emoji and the text will be kept together.
Before:
After:
=> Avoid line break between emoji and (un)read/(un)star links

ui/static/js.go, ui/static/js/nav_handler.js
Hello @fguillot,
I'm opening this pull request mainly to gather feedback about this behaviour. It's been useful for my use-case but I wonder if others would find it helpful.
When using the prev/next hotkeys, I usually open some articles in the background with the browser hotkey (ctlr+return). Focusing the main article link makes it possible, and it somewhat helps fixing #148.
I tested this both on Chrome and Firefox, but not on Safari nor Edge.
=> Focus links on pressing prev/next hotkeys

ui/static/js.go, ui/static/js/keyboard_handler.js
Fixes #260 
Shift was is not ignored on purpose, because it is needed to actually press some of the hotkeys on different keyboard distributions.
Tested on Chrome and Firefox.
=> Ignore hotkeys containing Control, Alt or Meta keys

template/functions.go, template/functions_test.go
- 15 days now is "15 days" rather than "3 weeks" ago.
- 32 days is now "1 month" rather than "2 months" ago.
- 366 days is now "1 year" rather than "2 years" ago.
Closes #267
=> Improve time since post date displays.

ui/entry_scraper.go
I haven't test the code and it's my first try in Golang. :)
It applies Rewriter rules on manual "Fetch Original Content", as done in https://github.com/miniflux/miniflux/blob/master/reader/filter/filter.go
(By the way, shouldn't there be a wrapper that calls scrapper, rewriter and sanitizer at once?)
=> Update entry_scraper.go to fix #284

http/client/response.go
Consider the feed http://planet.haskell.org/atom.xml
- This is a UTF-8 encoded XML file
- No encoding declaration in the XML header
- No Unicode byte order mark
- Served with HTTP Content-Type "text/xml" (no charset parameter)
Miniflux lets charset.NewReader handle this. The charset package implements the HTML5 character encoding algorithm, which, in this situation, defaults to windows-1252 encoding if there are no UTF-8
characters in the first 1000 bytes. So for this feed, we get the wrong encoding.
I inserted an explicit "utf8.Valid()" check, which fixes this problem.
=> Make UTF-8 the default encoding for XML feeds

reader/atom/atom.go, reader/atom/parser_test.go
Miniflux couldn't deal with XHTML Summary elements.
- Make Summary an 'atomContent' field
- Define an atomContentToString function rather than inling it three times
- Also properly escape special characters in plain text fields.
The attached feed contains an example of an XHTML Summary element (the post with the title "Happy New Years from MMH!").
[planet-haskell.xml.txt](https://github.com/miniflux/miniflux/files/2719649/planet-haskell.xml.txt)
=> More robust Atom text handling

database/migration.go, database/sql.go, database/sql/schema_version_20.sql, database/sql/schema_version_22.sql, storage/entry.go, storage/entry_query_builder.go, ui/search_entries.go
Hi, 
This PR improved search result, which makes the results ordered by relevance, should work for all languages.
This PR improves search only for new entires, because the following only affects  new entires:
```sql
SET document_vectors = setweight(to_tsvector(coalesce(title, '')), 'A') || setweight(to_tsvector(coalesce(content, '')), 'B')
```
---
PS: 
To make Chinese search work, user needs a customized `postgres` database, which enables `zhparser` plugin, and the database configured to use this parser by default. Or, users will find nothing while searching with Chinese.
Here is a [docker image](https://github.com/qjebbs/zhparser-docker) used by me, in case you want to put it in wiki or document.
```bash
git clone https://github.com/qjebbs/zhparser-docker
cd zhparser-docker
docker build …
```
=> Improve search results

storage/entry.go
I have plenty of space on my VPS, and was surprised when I suddenly could not find the article I read yesterday. Now ARCHIVE_READ_DAYS="-1" disables the auto-remove feature.
I don't know how to test this properly, but it should work.
=> Allow users to disable auto-remove

reader/sanitizer/sanitizer.go, reader/sanitizer/sanitizer_test.go
This lets the "open on YouTube" button work in YouTube embeds.
=> add 'allow-popups' to iframe sandbox permissions

template/common.go, template/html/common/layout.html
hello :wave: cheers for the great work on miniflux !
When using miniflux behind a proxy with auth, I noticed that manifest requests were failing (401) - preventing the PWA popup from showing up. This PR allows to simply pass the auth header along, so the request 200s again, and the PWA manifest successfully loads :+1:
=> pass auth header to manifest request

reader/opml/serializer.go, reader/opml/serializer_test.go
At the moment, miniflux doesn't sort names of feed categories, when you export an OPML file.
This will lead to dirty and cumbersome diffs if you try to regularly update your OPML xml file in any version control system.
The PR fixes this behaviour.
=> Sort feed categories before serialization

reader/atom/parser.go, reader/opml/parser.go, reader/parser/format.go, reader/rdf/parser.go, reader/rss/parser.go
Every once in a while, one of my feeds would throw an XML parse error because it used `&nbsp;` or some other HTML entity. I feel Miniflux should be lenient here, and Go already has a handy hook to make this work.
=> Accept HTML entities when parsing XML

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter_test.go
This rewrite rule would change this:
to this:
<figure><img><figcaption><foo></figcaption></figure>
The image title needs to be properly escaped.
=> addImageTitle: Fix HTML injection

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter.go, reader/rewrite/rewriter_test.go, reader/rewrite/rules.go
Dinosaur Comics (qwantz.com) likes to hide jokes in mailto: links, but
miniflux's sanitizer strips those out. This new rewrite function works around this problem.
=> add_mailto_subject: New rewrite function

http/response/builder.go, ui/proxy.go
The image proxy buffered the whole image before sending it to the
browser. If the image is large and/or hosted on a slow server, this
meant a long delay before the user's browser could display anything.
(It might be cleaner to just remove the buffering in http/client, and put a `defer resp.Body.Close()` in every caller. If you want, I can update the pull request to implement this.)
=> Implement streaming responses in the image proxy

config/config_test.go, config/options.go, config/parser.go, service/scheduler/scheduler.go, storage/session.go, storage/user_session.go
Resolves #443.
Adds a environment variable, `REMOVE_SESSIONS_DAYS`, to configure the number of days to keep Sessions and UserSessions around before removing them.
Let me know if there are any other tests you'd like to see added, or if you have any other comments.
=> Add config for days to remove sessions

config/config_test.go, config/options.go, config/parser.go, service/scheduler/scheduler.go
Per https://github.com/miniflux/miniflux/pull/445#issuecomment-530646166, adds an informal namespace to the cleanup config variables.
The config parser logs a warning when the user uses a deprecated variable. It also ignores the value from a deprecated variable if it has already been set using the corresponding non-deprecated variable (and logs another warning).
Let me know if you have any comments. It seemed like (if this is desired) that it'd be best to get in before the changes from #445 are released.
=> Add "namespace" to cleanup-related config variables

reader/atom/parser.go, reader/atom/parser_test.go, reader/opml/parser.go, reader/opml/parser_test.go, reader/rdf/parser.go, reader/rdf/parser_test.go, reader/rss/parser.go, reader/rss/parser_test.go
This change should improve parsing of broken XML feeds.
See https://golang.org/pkg/encoding/xml/#Decoder
=> Disable strict XML parsing

storage/entry.go, storage/feed.go
During feed creation, duplicated entries will generate an SQL contraint error.
This change ignore the duplicated entry to avoid showing an error.
=> Avoid constraint error when having duplicate entries

ui/static/js.go, ui/static/js/keyboard_handler.js
fixes https://github.com/miniflux/miniflux/issues/258 
Now if you have something that captures your keyboard events by default, we prevent that capturing from happening when we are trying to do shortcuts. We don't capture keyboard events that are not used by shortcuts. This matches the behavior in gmail which I expect is what most users will expect.
=> call preventDefault() when the user is trying to enter a keyboard shortcut

ui/static/js.go, ui/static/js/app.js
This is just an idea, what do you think if `v` would open the link in the current tab if you are already viewing a particular entry? 
My assumption is that when you are moving around a list of entries (say "unread" or "feed"), pressing `v` opens url in a new tab so that you can later go back to the list. But if you are already reading a particular entry in full screen, you probably press `v` to go that page to interact with it (read article comments, leave a message on forum, etc.), and it makes more sense to open the link in the current tab.
This would also improve upon #244 to assist with #148. You can open links with `Ctrl+Enter` and then press `v` on those pages.
=> Make "v" open link in the current tab on entry page

fever/handler.go
This PR fix a Fever Sync problem.
When a client, like `Reeder`, tries to mark an item which is removed on `Miniflux`, the server doesn't response OK. This may terminate the sync process, the PR fixes it.
=> fix Fever API of marking removed entries

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter_test.go
This is already done before in <media:description>.
=> Do no rewrite Youtube description twice in "add_youtube_video" rule

reader/xml/decoder.go, reader/xml/decoder_test.go
I encounter similar problem with #492 by `"XML syntax error on line xxx: illegal character code U+0008"`, this PR fix it：
`xml.Decoder.CharsetReader` only applies to non-UTF-8 data, so it did't filter invalid runes for UTF-8 data
=> filter valid XML char for utf8

reader/scraper/scraper.go, reader/scraper/scraper_test.go, reader/scraper/testdata/iframe.html, reader/scraper/testdata/iframe.html-result, reader/scraper/testdata/img.html, reader/scraper/testdata/img.html-result, reader/scraper/testdata/p.html, reader/scraper/testdata/p.html-result
This fixes the issues below:
---
If the parent element has multiple \<img/iframe>'s inside it, the scraper will return the parent element multiple times.
```css
<div id="_imageList">
<img><img><img><img><img>
</div>
```
`#_imageList > img` will cause the scraper to return the \<div> element five times.
---
When scraping \<p> elements the \<p> gets stripped leaving only the text which breaks formatting.
```css
<article>
<p>Example!</p>
<p>Text Here.</p>
<p>More Text.</p>
</article>
```
`article > p` will return "Example!Text Here.More Text.".
=> Return outer HTML when scraping elements

reader/atom/atom.go, reader/atom/parser_test.go
Show comments URL for Atom feeds as per RFC 4685.
See https://tools.ietf.org/html/rfc4685#section-4
Note that only the first link with type "text/html" is taken into consideration.
=> Add support for Atom 'replies' link relation

http/client/client.go, http/client/response.go, http/client/response_test.go, reader/feed/handler.go, reader/parser/parser_test.go, reader/subscription/finder.go, url/url.go, url/url_test.go
- Make sure query strings parameters are encoded
- As opposed to the standard library, do not append equal sign for query parameters with empty value
- Strip URL fragments like Web browsers
=> Normalize URL query string before executing HTTP requests

Dockerfile, Makefile
- Keep the Dockerfile standard and avoid external dependencies
- Use build args instead of Sed
- Bump Alpine Linux to version 3.11
- Always use the latest version of Golang
=> Remove dependency on Sed to build Docker images

reader/atom/atom_10.go, reader/atom/atom_10_test.go, reader/rss/parser_test.go, reader/rss/rss.go, url/url.go, url/url_test.go
Some feeds are using invalid URLs (random text).
=> Allow only absolute URLs in comments URL

ui/static/js.go, ui/static/js/app.js
This changes it so the current item selection wraps around to the front or back of the list when navigating a list view (i.e. with keyboard shortcuts j/k/n/p).
At present, navigating off the end of a list deselects the current item (so there ends up being no currently selected item). In the event of an accidental overrun of the end of the list (such as by navigating too fast or holding down the key), the last item of the list will be deselected, and on the next key press (which might be near-immediate) the first item of the list is selected (since there are no currently selected items). This is a de facto wrapping, but only in one direction, and if it occurs the user is forced to re-navigate through the entire list. With wrapping, the user could simple navigate backwards through the top …
=> Wrap around when navigating with keyboard shortcuts on a list view

ui/static/js.go, ui/static/js/app.js
At present, when the 'v' shortcut is used on the list of starred pages, the original article opens in a new tab and the currently selected item advances down the list (in the unseen tab). To me, it seems more intuitive to not advance the item when using the starred list. The user may close the original article's tab and wish to further interact with the item (such by unstarring it), and be unaware that the selected item is now different.
(I, at least, have unintentionally--and sometimes unknowingly--unstarred the wrong items due to the current behavior.)
Additionally, there is less of a sense of progress through items when working with starred items as compared to the unread list. Users have starred those items for a reason, and I would guess most users do not work their way through the …
=> Don't move to next item when opening original on starred list

ui/entry_unread.go
Hosted miniflux don't keep read entries for long. If I leave my PC at
home on an unread entry, read everything pending at work and get back
to home later, when I click "next", I get a bare 404 error. I have to
go back to /unread myself. I think it would be more user friendly (but
maybe a bit suprising) to go directly to /unread in this case.
Note that I didn't test the change. It seems trivial to me and I think you'll be faster than me to test (or to reject if you think that's a bad idea).
=> Redirect to /unread when getting a 404 for an unread expired entry

database/migration.go, database/sql.go, database/sql/schema_version_26.sql, model/entry.go, model/entry_test.go, storage/entry.go, tests/entry_test.go, ui/history_entries.go
With these changes, the history view will show entries in the order in which they were read.
This is implemented by adding a changed_at field in the Entries table which tracks when the entry's metadata was changed.
I did this because I often had a hard time finding an entry again after it was marked as read (accidentally or not), but this would also partially address issue #453 and perhaps #298 and #417.
=> History: show entries in the order in which they were read

template/html/common/entry_pagination.html, template/html/common/pagination.html
While this is widely documented for SEO reason, it also helps for
accessibility. Notably, if you are using tools like Vimium to browse
using only the keyboard, these hints help to select the links. It's
all the more useful when the text is not in English.
=> Use rel=prev/next on pagination link

config/config_test.go, config/options.go, config/parser.go, ui/middleware.go, ui/ui.go
Auth Proxy allows to authenticate a user using an HTTP header provided
by an external authentication service. This provides a way to
authenticate users in miniflux using authentication schemes not
supported by miniflux itself (LDAP, non-Google OAuth2 providers, etc.)
and to implement SSO for multiple applications behind single
authentication service.
Auth Proxy header is checked for the '/' endpoint only, as the rest are
protected by the miniflux user/app sessions.
Closes #534
=> Implement support for authentication via Auth Proxy

api/api.go, api/feed.go, api/handler.go, service/httpd/httpd.go
Adds refreshAllFeeds to the API, following the suggestion given in the comments of #359.
This provides a way to remotely trigger a background refresh of all feeds. This can be useful in a situation where a more complex refresh schedule is needed, or where the miniflux process is subject to aggressive sleep policies (such as free heroku dynos #307, or on GAE #324).
=> Add refreshAllFeeds to the API

reader/scraper/rules.go
By default fetching original content for wdwnt.com results in a snippet of the comments section, this rule captures the article content.
=> Addition of scraper rule for wdwnt.com

reader/scraper/rules.go
RayWenderlich.com is a popular developer's community for iOS and Android developers. The default rule results in "GROUP GROUP GROUP GROUP…" instead of the content posted on the blog.
=> Added scraper rule for RayWenderlich.com

reader/scraper/rules.go
The default rule results in blank content.
=> Added scraper rule for financialsamurai.com

locale/translations.go, locale/translations/de_DE.json
This just fixes a small typo in the newly added option to ignore HTTP-cache when fetching feeds.
Seems as if dutch was used by accident.
=> Fix typo in german translation

template/html/category_feeds.html, template/views.go
In the category>feeds page, go to entries of the category instead of the all categories page.
Fixed issue #659
=> Add a link to the category>feeds page, to go to entries of the category

oauth2/profile.go, storage/user.go
This remove keys previously created, for example `google_id`.
=> Fix regression: the entire hstore field is replaced when updating settings

api/api.go, api/middleware.go
Could not make Gorilla's built-in CORS handler work therefore added a simple middleware function to set the required (very permissive) CORS headers and a blank reply to the preflight requests (OPTION).
Closes #675
=> Added CORS support to API. 

fever/handler.go
(contd due to overly long commit msg) handleUnreadItems
=> Fixes #701 now uses getEntryIDs instead of getEntries in fever

template/common.go, template/html/bookmark_entries.html, template/html/categories.html, template/html/category_entries.html, template/html/category_feeds.html, template/html/common/feed_list.html, template/html/edit_feed.html, template/html/entry.html, template/html/feed_entries.html, template/html/history_entries.html, template/html/search_entries.html, template/html/shared_entries.html, template/html/unread_entries.html, template/views.go
This pull request adds the `dir=auto` attribute to the entry title, source, and content in the [`entry.html`](template/html/entry.html) template. This allows the browser to determine the text direction for each of these elements depending on the content, so articles in languages written from right-to-left such as Arabic and Hebrew are easier to read. Fixes #664
=> Add support for RTL feed content

reader/rss/parser_test.go, reader/rss/rss.go
In the vast majority of cases, the default entry title is correct.
Ignoring <media:title> avoid overriding the default title if they are different.
=> Ignore <media:title> in RSS 2.0 feeds

cli/create_admin.go, config/options.go, config/parser.go, miniflux.1
Secret keys are often exposed as a file in containerized environments.
=> Add support for secret keys exposed as a file

storage/entry_query_builder.go
When searching often you want to see recent entries, but there are a lot of old articles in results. This PR is attempt to make results for fresh by using published_at in a rank.
closes #397
=> Display recent entries first in search results

api/user.go, storage/user.go, ui/user_remove.go
Deleting large users might lock the tables in the hosted offering
=> API: Delete users asynchronously

reader/subscription/finder.go, reader/subscription/finder_test.go
YouTube doesn't expose RSS links anymore for new-style URLs.
=> Add workaround to find YouTube channel feeds

reader/rewrite/rewrite_functions.go, reader/sanitizer/sanitizer.go, reader/sanitizer/sanitizer_test.go
Fixes #641 by constructing invidious embed URL via regex. This change makes it necessary to allow iframes from same origin.
=> Make add_invidious_video rule applicable for different invidious instances

template/html/unread_entries.html, template/views.go
#360 fixes #345. But they are only for Feed and Category view, the same offsetting problem still exists for the Unread view for all feeds.
There should only be unread entries in the Unread view, so the `data-show-only-unread` attribute of the "Mark Page As Read" link is hardcoded to be `1`
=> Reload page after making page as read when showing unread entries

reader/date/parser.go
Parse "PDT" correctly for feeds in US Pacific time while daylight savings is in effect.
=> handle Pacific Daylight Time in addition to Pacific Standard Time

http/client/client.go
Reducing these values avoid going over the max number of file descriptors when refreshing lot of feeds
=> Tweak default HTTP client transport timeout values

http/client/client.go
If not set HTTP_CLIENT_PROXY, use default http transport(which would get HTTP_PROXY/HTTPS_PROXY from env). Users only need to set HTTP_PROXY/HTTPS_PROXY to bypass traffic to their proxy(as set feed using proxy one by one is frustrating, if they had more than 250+ feeds!).
=> Fix: If not set HTTP_CLIENT_PROXY, use default http transport

reader/atom/atom_10.go, reader/atom/atom_10_test.go
Avoid encoding single quotes to HTML entities (&#39;).
Feed contents are sanitized after parsing.
=> Do not escape HTML for Atom 1.0 text content during parsing

packaging/docker/Dockerfile
This ensures that the relevant port is published when using `docker run -P`, Traefik's Docker integration etc
=> Reinstate EXPOSE instruction

http/client/client.go, reader/subscription/finder.go
Some websites redirects unknown URLs to the home page.
As result, the list of known URLs is returned to the subscription list.
We don't want the user to choose between invalid feed URLs.
=> Do not follow redirects when trying known feed URLs

packaging/debian/build.sh
The miniflux user is not created on new installations
=> debian package: add missing post-install script

packaging/systemd/miniflux.service
Folks using a unix socket could use /run/miniflux/miniflux.sock without permission issue
=> systemd: keep /run writeable

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter.go, reader/rewrite/rewriter_test.go
The rule should be formatted like this:
`replace("search term"|"replace term")`
Standard golang regex and replace syntax can be used.
I think this will be useful for small rewrite cases which aren't covered by the existing rewrite rules. 
My specific use-case is for webtoons.com: replacing `webtoon` with `swebtoon` fixes the image src links and renders them properly..
=> Add rewrite rule replace for custom search and replace

config/options.go, config/parser.go, http/client/client.go, http/client/client_test.go, miniflux.1
Addresses #880. 
Creates a new USER_AGENT config setting, which is used by the miniflux http client in the place of the default user agent, if set.
=> Add support for setting a global default User-Agent

client/core.go, database/migration.go, database/sql.go, database/sql/schema_version_42.sql, model/entry.go, model/entry_test.go, storage/entry_query_builder.go
Addresses #848.
Adds a "created_at" field to the entries table/model/API which corresponds to the time that miniflux created/scraped the entry.
Caveats:
- "created_at" is populated using the DB's "now()" timestamp via the column default. Please let me know if we'd like to explicitly send a "created_at" timestamp from miniflux.
- I wasn't sure if this should be "created_at" or "scraped_at", so I went with the name suggested in the original issue.
=> Add created_at field for entries

packaging/systemd/miniflux.service
This change makes it possible to `apt-get install miniflux`, `echo CERT_DOMAIN=fqdn >>/etc/miniflux.conf`, and immediately start accepting HTTPS traffic with Let's Encrypt and without any reverse proxies.
Currently, Miniflux's documentation is a little conflicted and suggests to either;
1. [Remove systemd directives](https://miniflux.app/docs/howto.html#privileged-ports) such as `NoNewPrivileges` to let the process bind to <1024 ports.
2. [Use a reverse proxy](https://miniflux.app/docs/howto.html#reverse-proxy) such as NGINX. Doing so requires additional complexity to use Let's Encrypt (i.e. certbot).
3. [Use an experimental Systemd Socket Activation](https://miniflux.app/docs/howto.html#systemd-socket-activation) - without clear options for using Let's Encrypt.
This pull request adds two …
=> Let's Encrypt improvements

reader/atom/atom_10.go, reader/atom/atom_10_test.go, reader/json/json.go, reader/json/parser_test.go, reader/rdf/rdf.go, reader/rss/parser_test.go, reader/rss/rss.go
Some technical blogs have titles like "`</some-title>`" or "`This is some <code>source code</code>`".
Miniflux was removing these elements which prevent rendering the title correctly.
=> Do not strip tags for entry title

miniflux.1
Tell user they can use -1 to keep all entries.
=> update help on CLEANUP_ARCHIVE_READ_DAYS and CLEANUP_ARCHIVE_UNREAD_DAYS

packaging/systemd/miniflux.service
This is safer than directly editing the package-supplied version.
See https://wiki.archlinux.org/index.php/Systemd#Editing_provided_units.
=> Use `systemctl edit` for editing systemd config file

model/feed.go, reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter.go, storage/feed.go, storage/feed_query_builder.go, ui/login_show.go, ui/oauth2.go
When working on #994 I noticed that some Go files are not formatted with
`gofmt`.
This PR fixes this.
=> Reformat some Go files

http/client/client.go
Bug introduced after refactoring.
See commit 16b7b3bc3e4237abbacdf8695a685ca9a03dc5bb.
=> ETag value is not set correctly in HTTP client (regression)

storage/entry.go
tsvector has a size limit of 1MB. See https://www.postgresql.org/docs/13/textsearch-limitations.html
Input text is now truncated to avoid this error:
"pq: string is too long for tsvector (1057834 bytes, max 1048575 bytes)"
=> Limit full-text search indexation to first 500K characters

reader/date/parser.go, reader/date/parser_test.go
The Washington Post has its feeds with EST, which is getting parsed by miniflux as UTC, and showing up as 8 hours off.
See http://feeds.washingtonpost.com/rss/politics for an example.
This fix applies a similar workaround for EST/EDT as was done for PST/PDT.
=> Update date parser to fix another time zone issue

reader/rss/parser_test.go, reader/rss/rss.go
Example: `&amp;#39;Text&amp;#39;`
=> Add workaround for entry title with double encoded entities

reader/sanitizer/sanitizer.go, reader/sanitizer/sanitizer_test.go
An iframe element never has fallback content, as it will always create a nested
browsing context, regardless of whether the specified initial contents are
successfully used.
https://www.w3.org/TR/2010/WD-html5-20101019/the-iframe-element.html#the-iframe-element
=> Remove iframe inner HTML contents

service/httpd/httpd.go, storage/certificate_cache.go
This cache is used only for ACME certificates.
Being explicit is always better.
=> Rename storage certificate cache

client/README.md, client/client.go, client/request.go, config/config_test.go, config/parser.go, generate.go, http/client/client.go, http/client/response.go, http/client/response_test.go, integration/pocket/connector.go, reader/encoding/encoding.go, reader/icon/finder.go, reader/parser/parser_test.go, reader/scraper/scraper_test.go, reader/xml/decoder.go, tests/import_export_test.go
Miniflux now requires at least Go 1.16 and io/util is deprecated.
https://golang.org/doc/go1.16#ioutil
=> Remove deprecated io/ioutil package

template/templates/common/feed_list.html
=> Avoid showing a broken image when there is no feed icon

template/templates/common/feed_list.html, template/templates/views/feed_entries.html, ui/ui.go
Why:
e1c9e6ccb4607eeab2 added the support to mark a feed as read from views
showing a list of feeds. However, at times it can be useful to mark an
entire feed as read from within the feed entry views, e.g. when wanting
to mark as read a feed that is dominating a category after examining a
number of entries in that feed
What:
Add an li element in feed_entries.html to allow marking the feed as read
The code has been copy pasted from e1c9e6ccb4607eeab2
This closes #721
=> feed_entries: Add mark feed as read option

template/templates/common/feed_list.html, ui/ui.go
Piggyback on the javascript used for POSTing to a url to obtain a more
consistent behavior with the other options in the feed list (e.g. remove
feed). That way, when a feed is marked as read, regardless which view
the request originated from (feeds list view vs category feeds list
view), we are redirected to the view we started from.
While at it, add a confirmation dialog to mark feed as read. It was
suggested in PR #1055 for the single feed option, but it probably makes
sense if it was in the feeds list view too.
This closes #1064 
=> Redirect to the view the request came from when marking feed as read

ui/static/js/app.js
This pull request is aimed at resetting scroll position to top when marking a page as read with "Show only unread entries" enabled.
Without this change, when marking a page as read the user must scroll to top in order to see the first items of the page just loaded. This is caused by the default behavior of the user agent of restoring scroll position[1].
[1]: https://www.w3.org/TR/html52/browsers.html#scroll-restoration-mode
=> Reset scroll position on mark page as read

reader/processor/processor.go, storage/entry.go
Should close #1056.
This will fix the issue I'm facing in #1056 but will continue fetching YT videos which don't have any word in the description (should have a reading time of 0 as per `calculateReadingTime`, unless the URL of the YT video counts as words) and for which the scraping failed.
=> Prevent YT scraping if entry already exists

cli/daemon.go, cli/sd_notify.go, go.sum, packaging/systemd/miniflux.service
Set the systemd startup type to `notify`, so that startup of followup units is delayed until Miniflux signals readiness. 
=> Implement readiness notification for systemd

ui/static/css/common.css, ui/static/css/dark.css, ui/static/css/light.css, ui/static/css/system.css
The contrast between background and purple for visited links was too
low (1.69). Use a brighter purple for the dark theme (contrast 6.87).
=> Use an appropriate color for visited links on dark theme

locale/translations/de_DE.json, locale/translations/en_US.json, locale/translations/es_ES.json, locale/translations/fr_FR.json, locale/translations/it_IT.json, locale/translations/ja_JP.json, locale/translations/nl_NL.json, locale/translations/pl_PL.json, locale/translations/pt_BR.json, locale/translations/ru_RU.json, locale/translations/tr_TR.json, locale/translations/zh_CN.json, model/category.go, storage/category.go, template/templates/views/categories.html
the number of feeds in the category is currently displayed twice, and a lot less
useful than the number of unread items in the category.
implements #512 
tested to one million feed entries, where the query takes around 150ms average.
translations are all copied from the page.feeds.unread_counter, which seemed like a reasonable idea.
=> show #unread per category in category list, not #feeds

cli/reset_password.go
User has been stored in CLI command, but the new password has never been assigned to user model. Kinda obvious bug/fix, but maybe not.
=> Fix password reset via CLI

template/functions.go, template/templates/common/layout.html
If the application is hosted behind a CDN like Cloudflare,
then all custom stylesheets is be the same for all users.
The random query string prevent the CDN to cache this.
=> Avoid custom stylesheet to be cached by third-party CDN

client/model.go, model/entry.go, storage/entry_query_builder.go
No issue
This is already stored and updated in the DB to render the History page but is currently not exposed through the API
=> Expose `changed_at` time through the API

reader/json/json.go, reader/json/parser_test.go
=> Fix #477: Fix truncate method used for title in JSON Feed parser

template/engine.go, template/functions.go, template/templates/common/layout.html, ui/view/view.go
Allow `hyphens` CSS property to work correctly. Also may improve screen reader
=> Add lang attribute to root html tag

http/response/builder.go, http/response/builder_test.go, template/functions.go, template/templates/common/layout.html, ui/static_stylesheet.go
Use inline CSS with a nonce and move CSP headers to a meta tag.
=> Avoid extra HTTP request for fetching custom stylesheet

ui/static/css/common.css
=> Firefox on Windows does not show the active link as bold

storage/feed.go, template/templates/common/feed_list.html, ui/static/css/common.css, ui/static/css/dark.css, ui/static/css/light.css, ui/static/css/system.css
categories are currently a bit unfriendly to use when they contain many feeds, most of which update rarely. it's not easy to find feeds with unread entries, so it seems prudent to highlight them specially (like feeds with errors are highlighted already), and to sort feeds with unread entries before feeds without unread entries.
=> improve category display a little

client/model.go
Comments URL for entries is returned by API, but has not avaliable in
the Go client. This PR fixes this.
=> client: expose comments_url entry field

template/templates/common/item_meta.html, ui/static/js/app.js
we show a "Saving ..." status while starring an entry, but not while marking an entry as read/unread. this can be a bit of an annoyance when saving the state takes longer than expected, and closing the tab for a feed aborts the request that would change a thing to read.
=> show "saving" labels for entry status button

database/migrations.go, locale/translations/de_DE.json, locale/translations/en_US.json, locale/translations/es_ES.json, locale/translations/fr_FR.json, locale/translations/it_IT.json, locale/translations/ja_JP.json, locale/translations/nl_NL.json, locale/translations/pl_PL.json, locale/translations/pt_BR.json, locale/translations/ru_RU.json, locale/translations/tr_TR.json, locale/translations/zh_CN.json, model/category.go, storage/category.go, storage/entry.go, storage/entry_query_builder.go, template/templates/views/edit_category.html, ui/category_edit.go, ui/category_update.go, ui/entry_update_status.go, ui/form/category.go, ui/static/js/app.js, ui/unread_entries.go
implement #447 
`SetEntriesStatusCount` could be folded into `SetEntriesStatus` as an `update ... returning`, but there's enough places in the code that don't need the extra info that it seemed like a good idea to keep them separate. translations from english to other languages by DeepL.
=> add option to hide categories from the global unread list

contrib/docker-compose/basic.yml, contrib/docker-compose/caddy.yml, contrib/docker-compose/traefik.yml
'start_period' for 'healthchecks' was added in Compose file version 3.4,
https://docs.docker.com/compose/compose-file/compose-versioning/#version-34
Bump docker-compose files' versions from 3.3 to 3.4
Without this, docker-compose (1.25 at least) returns
```
ERROR: The Compose file './contrib/docker-compose/caddy.yml' is invalid because:
services.db.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
```
=> contrib: Bump docker-compose version to 3.4

contrib/docker-compose/basic.yml, contrib/docker-compose/caddy.yml, contrib/docker-compose/traefik.yml
Allowing to override the image used in docker-compose files can allow
for richer and more easy local development/debugging sessions. The
docker image building process is already using the latest tag anyway,
making it really easy to build an image with a (set of) specific
commits. Using the above built image with the provided docker-compose
files isn't doable without modifications though. Add that support via
environmental variables.
=> contrib: Add support for a $MINIFLUX_IMAGE env var in docker-compose

locale/translations/en_US.json
Fix a typo, by adding the "in" part of the phrasal verb as the intent is
to notify the user that they are "logged" in in the system as user X and
not to notify them that they are "recorded"
=> Add "in" in "logged in" for en_US tooltip.logged_user

template/templates/views/categories.html, template/templates/views/category_entries.html, ui/category_mark_as_read.go, ui/ui.go
Why:
It is nice to have the ability to mark an entire category as read in the
UI. The API already exposes that functionality anyway, so for
consistency reasons, expose it in the UI as well
What:
Add a new handler in the UI to markCategoryAsRead() and amend views and
router to expose the functionality in the UI
=> ui: Expose markCategoryAsRead

reader/json/json.go, reader/json/parser_test.go
The [JSON Feed 1.1 spec](https://jsonfeed.org/version/1.1) has deprecated the singular `author` field in favor an `authors` array. This PR checks for `authors` and uses that if present.
=> use authors entry for json 1.1 feeds

reader/subscription/finder.go
ATCOM netvolution WCM, probably alongside others, a CMS powering several
high profile and high traffic Greek news sites, among other sites,
publishes the RSS feed under /rss/. Add it to the list. It's generic
enough to allow us to assume other software might do it to
On a select set of 627 Greek news media sites (the infamous Petsas list),
adding this rule increased discoverability of RSS feeds by a factor of
2.61% (from 498 to 511).
=> Add /rss/ in finder's wellKnownUrls

reader/subscription/finder.go
The 1.1 version (https://jsonfeed.org/version/1.1) for JSON feeds defines that feeds should have a MIME type of `application/feed+json` which Miniflux wasn't searching for. I've tested this on a few sites that have JSON feeds and Miniflux now finds them when scraping the page for meta tags.
=> Fix finding JSON feeds with new MIME type

reader/processor/processor.go, reader/scraper/scraper.go
The scraper doesn't use proxy event I choose "Fetch via proxy" when create a subscription.
=> add proxy arg in scraper.Fetch

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter.go, reader/rewrite/rewriter_test.go
Hello!
A lot of sites contain elements I want to filter out, when scraping for original content.
In many cases you can get away with chained `:not(...)` selectors, however, in some cases it gets pretty complex or impossible without introducing new problems (e.g. duplicated elements).
I found at least one open issue describing the same problem: #472.
With this pull request I propose the addition of a `remove(".selector, #another_selector")` rewrite rule.
I tried my best to stay compatible with the previous rewriter rule syntax, while introducing a new custom rule with an argument potentially containing commas. Instead of splitting rules on each comma, now the go std library token scanner is used to read identifiers and strings. Since the `Rewriter` function …
=> Add rewrite rule to remove dom elements

http/client/client.go, url/url.go, url/url_test.go
I can't remember why this change was done.
Let's use only the standard lib.
It seems to break URL like this one: https://www.deimeke.net/dirk/blog/index.php?/feeds/index.rss2
=> Remove RequestURI() hack

storage/entry_pagination_builder.go, ui/entry_bookmark.go, ui/entry_category.go, ui/entry_feed.go, ui/entry_read.go, ui/entry_search.go, ui/entry_unread.go
Users can change the entry sorting column in the pagination of the list page, but the paging navigation of the detail page is not consistent with this.
=> Fix inconsistent pagination

ui/static/css/common.css
---
This fixes the `<template>` elements being visible on older browsers, specifically the PlayStation Vita browser in my case, though it looks anything pre-2015 or so is probably affected. It shouldn't have any impact in modern browsers as the CSS is identical to Safari and Chrome at least's default for templates, just `display: none;`.
Apologies if I didn't put it in a good place in the CSS file, the modals are what the templates are and it seems the element selectors are usually being done first so I put it right below the `/* Modals */` comment since that seemed like the best place to me.
I would have just used custom CSS to fix this, but custom CSS is broken in the Vita browser and I can't figure out why, so since it's a minor change with no downsides …
=> Fix templates being visible on old browsers

config/config_test.go, config/options.go
Addresses #1224. Changes `-config-dump` to use `KEY=VALUE` format, so that the output of `-config-dump` is compatible to be used as the input to `-config-file`.
Example:
```sh
$ ./miniflux-darwin-arm64 -config-dump
ADMIN_PASSWORD=
ADMIN_USERNAME=
AUTH_PROXY_HEADER=
AUTH_PROXY_USER_CREATION=false
BASE_PATH=
BASE_URL=http://localhost
BATCH_SIZE=100
CERT_DOMAIN=
CERT_FILE=
CLEANUP_ARCHIVE_BATCH_SIZE=10000
CLEANUP_ARCHIVE_READ_DAYS=60
CLEANUP_ARCHIVE_UNREAD_DAYS=180
CLEANUP_FREQUENCY_HOURS=24
CLEANUP_REMOVE_SESSIONS_DAYS=30
CREATE_ADMIN=false
...
```
Technically, this is a breaking change, since if a user has a script that relies on `KEY: VALUE`, this change will break that.
---
=> Change -config-dump to use KEY=VALUE format

model/theme.go, template/functions.go, template/templates/common/layout.html, ui/static_manifest.go
Hey folks,
as Apple introduced with iOS 15 and Safari 15 support for the "theme-color" property, I noticed that the theme color is always the value for the light theme, when you select a "system" theme:
I introduced a color scheme parameter, and added a second meta-tag with the correct media.
As there is no official way to set the theme color for the dark mode in the [web manifest yet](https://github.com/w3c/manifest/issues/975), I just passed there the parameter "light", as this will not change the current behavior.
=> Add support for theme color based on preferred color scheme of OS

storage/feed.go
This PR orders disabled feeds to last, which:
- disabled feeds last, even if they have errors.
- in disabled feeds section, the error feeds are still first
- simplify the order codes, but introduced slightly change that feeds who has more errors are first
=> order disabled feeds to last

packaging/systemd/miniflux.service
These changes will add a `/run/miniflux` directory for the Unix socket bind.
I've only tested the Debian package generation on amd64. I don't have different hardware.
The Fedora package needs more work, `nginx` on Fedora uses the `nginx` group, which isn't present without `nginx` installed. I'm not well versed on RedHat systems, so I'll open this as a draft for now, to figure out whether to not add this file at all or use some other group, or some other solution.
=> add systemd-tmpfiles config file

packaging/systemd/miniflux.service
This change tightens systemd sandboxing and updates comments in the `miniflux.service` unit file.
I run Miniflux with this configuration for more than a year and haven't noticed any issues.
---
=> Tighten systemd sandboxing and update comments in miniflux.service

packaging/systemd/miniflux.service
`SystemCallFilter=@system-service` is not supported on older systemd versions and causes crashes on them.
Fixes #1297.
=> packaging: remove SystemCallFilter from miniflux.service

reader/scraper/rules.go
Feed: https://ikiwiki.iki.fi/feed.php?linkto=current&ns=uutiset%3Ablog&num=5
Example page: https://ikiwiki.iki.fi/uutiset/blog/20210923100421viiveita
(To clarify, I'm not a representative of iki.fi although I have an email address in the domain. This is a nonprofit association that offers email forwarding addresses, and the rss feed in question contains news for their members.)
I try to follow the guidelines:
=> Add scraper rule for ikiwiki.iki.fi

ui/feed_icon.go, ui/proxy.go
- SVG images could contains Javascript. This CSP blocks inline script.
- Feed icons are served using `<img>` tag and Javascript is not interpreted.
See https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image#restrictions
=> Add Content-Security-Policy header to feed icon url

template/templates/common/item_meta.html, template/templates/views/entry.html
Why:
A user might want to unshare a specific entry. Navigating to the shared
entries page requires a mental context switch, whereas having the
ability right in the entry page makes it easier.
What:
Add an extra \<li> element to display the unshare icon and link in the
entry view as well as the item_meta template. The latter is shared for
multiple pages listing entries, e.g. bookmarks, feed entries, search,
history etc.
The functionality already exists for the shared entries page, we are
just expose it in a couple more places
Signed-off-by: Alexandros Kosiaris <akosiaris@gmail.com>
=> Expose entry unshare in the entry and list views

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter.go, reader/rewrite/rules.go, reader/scraper/rules.go
Quantamagazine.org is a somewhat complex React site, but with these changes I can see the text, images and videos in all the stories that are currently visible in the rss feed. This adds a heuristic rule for detecting Youtube ids in JavaScript and enables it for quantamagazine.org.
=> Scrape and rewrite rules for quantamagazine.org

config/options.go, config/parser.go, miniflux.1, reader/rewrite/rewrite_functions.go, reader/rewrite/rules.go, reader/sanitizer/sanitizer.go
This solves issue #893 since invidio.us has closed down. You can use a custom Invidious instance by setting the `INVIDIOUS_INSTANCE` variable, the default value is `yewtu.be`, it could be discussed if needed.
This is my first contribution so I hope the code is not dirty.
=> Custom invidious

ui/static/js/touch_handler.js
After swiping an article, code will reset the style.opacity and style.transform properties to cancel the swipe. This is not necessary to do this if the user swipes far enough to toggle entry status. This creates a jarring effect on slower mobile connections.
https://user-images.githubusercontent.com/11655457/149604464-d46d1485-a232-4473-8811-df84415dc57c.mp4
With the PR the code won't execute when the user dismisses the article.
https://user-images.githubusercontent.com/11655457/149604540-ef882408-5fbb-4238-bc49-ba531dce413b.mp4
=> Do not reset touch-item if successfully swiped

reader/atom/atom_10.go, reader/atom/atom_10_test.go
Trim space around CDATA elements before extracting the CharData.
This problem was discovered when reading https://www.sethvargo.com/feed.xml.
Title and Summary fields have newlines and space between the <title>
element and the CDATA element. e.g.
```
<title>
<![CDATA[Entry title here]]>
</title>
```
This meant the title of the feed was coming into MiniFlux as,
```
<![CDATA[Entry title here]]>
```
=> Handle atom feed with space around CDATA

locale/translations/de_DE.json, locale/translations/el_EL.json, locale/translations/en_US.json, locale/translations/es_ES.json, locale/translations/fi_FI.json, locale/translations/fr_FR.json, locale/translations/it_IT.json, locale/translations/ja_JP.json, locale/translations/nl_NL.json, locale/translations/pl_PL.json, locale/translations/pt_BR.json, locale/translations/ru_RU.json, locale/translations/tr_TR.json, locale/translations/zh_CN.json, template/templates/views/about.html, ui/about.go
There seems to be a steady trickle of minor security bugs in the Golang crypto/x509, crypto/tls, and net/http packages, and every time another one drops I wonder if I need to rebuild Miniflux to update the Go standard library. I know I can retrieve the Go version from a miniflux binary by calling it with the -info flag, but I'm not always in a position to SSH into the box that's running my copy of miniflux, so it would be nice to find the Go version on the /about page.
Please let me know if you think the Go version should be hidden behind the IsAdmin flag (as the Postgres version is). 
Translations are copy-paste from the equivalent Postgres version string, and might not account for grammatical gender, etc.
=> Display Go version on /about

template/templates/views/bookmark_entries.html, template/templates/views/category_entries.html, template/templates/views/entry.html, template/templates/views/feed_entries.html, template/templates/views/history_entries.html, template/templates/views/search_entries.html, template/templates/views/unread_entries.html, ui/static/css/common.css
Enable users to move to prev/next page without having to scroll all the
way to the bottom of the page.
Furthermore, ensure consistency with entry.html which has top and bottom
pagination.
=> Add pagination on top of all entries. Closes #1305.

api/api.go, api/entry.go
Hi,
I needed to fetch the original article via API. I also came across #1114 so I have implemented it.
Of course a client API could fetch the article by itself, but the api is usefull (cors, apply feed rules, could also proxy image)
Regards,
Pascal
=> Fetch original article with api, fix #1114

ui/static/js/touch_handler.js
In my previous pull request, I accidentally introduced a regression where swiping an article not in unread (where swiping does not delete) leaves the article transformed. This pull request resets touch item if the page is not /unread or the distance was less than or equal to 75.
=> Fixed regression: reset touch-item if not in /unread

reader/rewrite/rewrite_functions.go, reader/rewrite/rewriter.go, reader/rewrite/rewriter_test.go
This new rewrite rule allows to add an embedded player for podcast episodes from a castopod instance.
You can test it with [this feed](https://podcast.picasoft.net/@la_voix_est_libre), you have to add `add_castopod_episode` in rewrite rules.
=> Add a rewrite rule for castopod episodes

template/templates/views/add_subscription.html, template/templates/views/edit_feed.html, ui/static/css/common.css
Preview: 
We could optionally extract those URLs to a template for reuse, but I figured it's cleaner not to since they're only used in two places.
=> Add links to scraper/rewrite/filtering docs when editing feeds

template/templates/common/feed_menu.html, template/templates/views/categories.html, template/templates/views/category_entries.html, template/templates/views/category_feeds.html, template/templates/views/create_category.html, template/templates/views/edit_category.html, template/templates/views/edit_feed.html, template/templates/views/feed_entries.html, template/templates/views/sessions.html, template/templates/views/unread_entries.html, ui/static/bin/sprite.svg
Notes:
- Only added pre-existing icons from `sprite.svg`. If desired, we could incorporate more icons from https://tabler-icons.io/, but opted to keep it simple / minimal for now.
- Only added the unambiguous items. Some examples are ambiguous, for example: ( ) Mark this page as read vs ( ) Mark all as read. There is a "mark all as read" icon already, however it could be deemed confusing to add both of them in the same context for two different actions, as the actions are very similar. I leave this open for debate.
- If you think there are more places to add existing icons to I could've missed, feel free to point them out.
Sample view attached below.
=> Add a few existing icons to menus

template/templates/common/layout.html, ui/static/css/common.css
@fguillot curious if you like this change.
To add new feeds from mobile, you first need to click "Feeds" (which can be slow once you have lots of feeds, as all feeds are loaded without any pagination), and then "Add subscription". This change makes it easier to go straight to the "Add subscription" page, without needing to list all feeds.
We could potentially improve it a bit by adding some styling to the `(+)` (maybe by fading it out a bit).
=> RFC: Add (+) action next to Feeds to quickly add new feeds

template/templates/common/entry_pagination.html, template/templates/common/pagination.html, ui/static/css/common.css
Whenever the "prev" and "next" buttons have no hyperlink, decrease their
opacity to signal that they lead to nowhere.
This signal is stronger and more obvious than the current one which
merely removes the underline decoration from the text.
This patch is an improvement on top of
https://github.com/miniflux/v2/pull/1107
=> Gray out pagination buttons when they are not applicable

reader/icon/finder.go, reader/icon/finder_test.go
Fetching icons crashes with "slice bounds out of range" error if no encoding is specified.
=> Fix invalid parsing of data URL

ui/static/css/common.css, ui/static/js/touch_handler.js
This modifies the user experience a bit when swiping an entry read/unread in article lists, but I think it makes the interface more consistent with operating systems that use touch (e.g. iOS/iPadOS). It works especially well for the non-unread lists (individual feeds/categories, showing all, etc.).
* Removes opacity transition when swiping an entry read/unread.
* Adds "resistance" to the swiped entry when the 75 px threshold is reached. The entry moves freely with the user's finger, but as soon as the threshold is reached the amount it moves decreases with distance.
* If the user changes their mind, the entry gently snaps back to place using CSS effects.
* Fixes an issue in which a swiped entry could not be moved back to its starting position by the user when …
=> Make swipe gestures feel more natural.
